@startuml
'https://plantuml.com/class-diagram

class Identite{
-String NIP
-String nom
-String prénom
}
class Etudiant{
-HashMap<String:Matière,List<Double>:notes> résultats
}
class Formation{
  -String idformation
  -HashMap<String:matiere,Integer:coefficient> matières
}

Etudiant -> Identite : -Identite idEtu
Etudiant -> Formation : -Formation form



@enduml