@startuml
'https://plantuml.com/class-diagram

class Identite{
-String NIP
-String nom
-String prénom
---
+Identite()
+Identite(String,String,String)
+toString()
}

class Etudiant{
-HashMap<String:Matière,List<Double>:notes> résultats
---
+Etudiant()
+Etudiant(Identite, Formation, HashMap<String,ArrayList<Double>)
+ajouterNote(String, double)
+calculerMoyenne(String)
+calculerMoyenneGenerale()
}

class Formation{
  -String idformation
  -HashMap<String:matiere,Integer:coefficient> matières
  ---
  +Formation(String)
  +ajouterMatiere(String, Integer)
  +supprimerMatière(String)
}

class Groupe{
---
+Groupe()
+ajouterEtudiant(Etudiant)
+supprimerEtudiant(Etudiant)
+calculerMoyenneGroupe (Matière): double
+calculerMoyenneGeneraleGroupe: double
}

Groupe -> Etudiant : -Etudiants etu
Groupe -> Formation : -Formation form
Etudiant -> Identite : -Identite idEtu
Etudiant -> Formation : -Formation form



@enduml